name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-in: [self-hosted, Linux, standard]
    name: "Test"
    steps:
      run: echo Build is complete
  deploy:
    runs-in: [self-hosted, Linux, standard]
    name: "Deploy staging"
    environment: staging
    steps:
      run: echo Deploy is complete
