name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Test"
    steps:
      - name: build
        run: echo Build is complete
  deploy:
    runs-on: ubuntu-latest]
    name: "Deploy staging"
    environment: staging
    steps:
    - name: deploy on staging
      run: echo Deploy is complete
