name: CI

on:
  push:
    branches: ["main"]

jobs:
  Build:
    runs-on: ubuntu-latest
    name: "Build"
    steps:
      - name: build
        run: echo Build is complete
  Deploy_Staging:
    runs-on: ubuntu-latest
    needs: Build
    name: "Deploy staging"
    environment: staging
    steps:
      - name: deploy on staging
        run: echo Deploy is complete
  Deploy_Preprod:
    runs-on: ubuntu-latest
    needs: Build
    name: "Deploy preprod"
    environment: preprod
    steps:
      - name: deploy on preprod
        run: echo Deploy is complete
  Deploy_Prod:
    runs-on: ubuntu-latest
    needs: Build
    name: "Deploy prod"
    environment: prod
    steps:
      - name: deploy on prod
        run: echo Deploy is complete
  Flush cache:
    runs-on: ubuntu-latest
    needs: [Deploy_Prod, Deploy_Preprod, Deploy_staging]
    name: "Flsuh cache"
    steps:
      - name: Flush cache
        run: echo Flush cache is complete
